Cylc Obs Workflow
GEOS-ESM/swell pull request #101
Opened 2022-07-25 13:29 UTC by asewnath

## Description

Cylc workflow for preprocessing observation and satbias files into JEDI-compliant formats for SWELL experiments.

## Acceptance Criteria 

All observations for a given cycle should be retrieved in the Cylc run directory, preprocessed, and saved into the user's local R2D2DataStore with the correct datetimes

2022-07-26 19:38 UTC, danholdaway commented
@asewnath can you check on the coding norms please? It looks like that test is failing.

2022-07-26 19:42 UTC, danholdaway commented
In the list of changed files I see a few unexpected changes. For example a series of files in a directory called `/bin`. And then a bunch of files called `*.sw*`. Also the `satwind.yaml`. Could you remove those or revert them to be the same as develop?

2022-08-11 15:22 UTC, danholdaway requested changes
Just one small change request. Otherwise this runs for me and looks like it produces the correct thing.

2022-08-11 15:22 UTC, danholdaway commented on src/swell/suites/process_obs/experiment.yaml
> +experiment_root: /discover/nobackup/${USER}/JediExperiments/
```suggestion
experiment_root: /discover/nobackup/${USER}/SwellExperiments/
```
So it's consistent with the other experiments.

2022-08-15 14:12 UTC, asewnath commented
satbias processing isn't working properly due to HDF5 version mismatch errors

2022-08-15 18:46 UTC, danholdaway commented on src/swell/suites/retrieve_obs_list.py
> +from swell.configuration.configuration import return_configuration_path
What is the role of this file? I don't see it being referenced anywhere. And it seems like it's doing task like work so I'm nor sure it belongs in the suite directory.

2022-08-16 15:56 UTC, asewnath commented on src/swell/suites/retrieve_obs_list.py
> +from swell.configuration.configuration import return_configuration_path
I actually don't even remember why I made this file, it probably had to do with logic I made for the GUI sprint because, like you say, it wouldn't be in the suites directory otherwise. I'll delete that

2022-08-19 01:30 UTC, danholdaway approved these changes

2022-08-19 01:31 UTC, merged