Fix MarineVertInterp and update some modules to sky4
GEOS-ESM/swell pull request #176
Opened 2023-05-10 18:58 UTC by danholdaway

## Description

- Keep up with JEDI (https://github.com/JCSDA-internal/soca/pull/874/files)
- Keep up with Skylab (to version 4.0)

## Dependencies

N/A

## Impact

N/A

2023-05-10 20:47 UTC, jardizzo approved these changes

2023-05-10 20:51 UTC, Dooruk requested changes
Hofx and 3dvar worked on my end. I just had to make a new build with jedi_bundle 1.0.10. I will leave the Cylc test to you since you are already in queue.

2023-05-10 20:51 UTC, Dooruk commented on src/swell/deployment/platforms/nccs_discover/modules
>  module load eva/1.3.4
Eva is giving the following error:

`ABORT EvaFactory: Expecting to find a class called 'FigureDriver' in a file called '/discover/nobackup/dardag/JediOpt/src/eva/latest/src/eva/plot_tools/figure_driver.py' but no such file was found or an error occurred during import. `

`Reported error: No module named 'scipy.stats._hypotests_pythran'`

Same issue with EVA 1.3.5 as well.

2023-05-11 00:35 UTC, danholdaway commented on src/swell/deployment/platforms/nccs_discover/modules
>  module load eva/1.3.4
Thanks @Dooruk. I reinstalled `eva/1.3.5` using skylab 4 modules and that should hopefully fix that issue.

2023-05-11 00:35 UTC, danholdaway commented on src/swell/deployment/platforms/nccs_discover/modules
>  module load eva/1.3.4
...and also updated this branch to point to that version of eva.

2023-05-11 00:37 UTC, danholdaway commented
Since the nightly is already broken I'm going to merge this so we can see if it works tonight.

2023-05-11 00:38 UTC, merged