LETKF for single cycle
GEOS-ESM/swell pull request #256
Opened 2023-10-05 21:14 UTC by CEgerer93

## Description

Completes support of LETKF in `geos_atmosphere` for a single cycle.
Need to establish conventions for updated ensemble members before cycling in earnest.

## Dependencies

No dependencies, though the following needs to be addressed for an error-free `Cylc` workflow described by `suites/letkf/flow.cylc`:
- [ ] `EvaObservations`

## Impact

None.

2023-10-06 01:28 UTC, danholdaway commented
Thanks so much for adding this @CEgerer93. You can evaluate the Coding Norm and Code Testing failures on Discover. To do that you would install as follows:

Swell Code Testing:
``` shell
module use -a /discover/nobackup/drholdaw/opt/modulefiles/core/
module load miniconda/py39_23.3.1
pip install --prefix=/path/to/core/swell/version --no-cache-dir -r requirements-standalone.txt .
module load swell/version
swell_tests_code
```

Python Coding Norms
``` shell
cd /path/to/srd/swell/version
python pycodestyle_run.py
```

The YAML test can't be run on Discover so you have to look at the logs here. It looks like it doesn't like Jinja2 templates in the YAML but what you have is legit. Maybe we should ask @mathomp4 if he knows how to skip a file in the YAML linting.

2023-10-06 15:31 UTC, CEgerer93 commented
Thank you @danholdaway for the reminder on how to locally check the swell/python norms; minor changes, as expected.

To be clear, `swell_tests_code` isn't supported in a standard `swell` build? There are quite a few additional modules (e.g., `flake8`, etc.) required when installing for the swell code testing.

2023-10-06 18:25 UTC, danholdaway commented
@CEgerer93 that is correct. The problem is that we normally build swell with the spack-stack modules so swell is installed in a manner consistent with how things it will run (i.e. JEDI) are built. However I found that flake8, which the test needs, requires some versions of dependencies newer than what's in spack-stack. So until we can add more to the spack-stack modules we have two installs.

2023-10-06 20:07 UTC, CEgerer93 commented
Okay, great - that makes sense. I will await suggestions from Matt concerning YAMLlint.

2023-10-09 14:23 UTC, mathomp4 commented
I guess I'm a bit late to this, but it looks like you should be able to ignore a file with action-yamllint. Per https://github.com/ibiqlik/action-yamllint/issues/8, you might be able to add to `.yamllint.yml`:
```yaml
    allow-non-breakable-inline-mappings: true
  truthy: disable

  ignore: |
    src/swell/configuration/jedi/oops/LocalEnsembleDA.yaml
```

There actually seems to be a lot of different ways per https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths

If you anticipate more Jinja2/YAML files, might be best to start a `.yamlignore` file and use `ignore-from-file` perhaps?

2023-10-09 16:41 UTC, CEgerer93 commented
Thank you, @mathomp4 for your suggestions. @danholdaway has implemented a change to allow the yaml norms to pass.

I trust we will be sticking with just a single file with jinja2 conditional formatting. The ensemble-based schemes I am working to add into swell are the only components, as far as I can tell, that feature duplicate yaml entries based on what outputs are produced. A later version of [`fv3-jedi`](https://github.com/JCSDA-internal/fv3-jedi) will likely clear this up.

2023-10-10 14:47 UTC, danholdaway commented
Thanks @mathomp4 that suggestion works and is better than what I was doing since it doesn't diverge from the community maintained action for YAML linting.

2023-10-10 15:03 UTC, danholdaway requested changes
Thanks again for adding this great new feature. Just a few minor things to change please. Also, as I'm reviewing the code I realize that "letkf" might not actually be the correct nomenclature for the suite and tasks etc. Perhaps we should go with `LocalEnsembleDa` / `local_ensemble_da` ?

2023-10-10 15:03 UTC, danholdaway commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/geos_atmosphere.yaml
> +  letkf: fv3jedi_letkf.x
Should we call this `localensembleda: fv3jedi_letkf.x`? That would be consistent with the oops YAML name and what I think the application is actually called in JEDI.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  options:
Do we really want options here? Or should the user be free to pick any float they like?

2023-10-10 15:03 UTC, danholdaway commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  options:
Same comment for the two below.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  options:
For boolean questions we don't need to defer the options to each model since they will always be true/false. Can you set the options in the main `task_questions.yaml` instead? Same for next three questions.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  - true
Same as above.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/deployment/prep_suite.py
> +        'RunJediLetkfExecutable',
Could this be `RunJediLocalEnsembleDaExecutable`? For future proofing if this suite could be used for other things, like EnKF, GETKF etc.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/suites/letkf/flow.cylc
> +# Cylc suite for executing JEDI-based LETKF Algorithm
```suggestion
# Cylc suite for executing JEDI-based LocalEnsembleDA Algorithm
```

2023-10-10 15:03 UTC, danholdaway commented on src/swell/tasks/run_jedi_letkf_executable.py
> +        # Ensemble Localizations
As above I would suggest renaming the task to `run_jedi_local_ensemble_da_executable`.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +local_ensemble_inflation_mult:
As I alluded to in a previous comment not everything necessarily needs options. When it comes to numbers like floats and integers they might be omitted to allow users to pick anything they want. If you have options I think the type would generally need to be string and then drop list or check list. Perhaps we actually need to put some protection in place for that.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +  options: defer_to_model
boolean options don't need to be deferred.

2023-10-10 15:03 UTC, danholdaway commented on src/swell/utilities/render_jedi_interface_files.py
> +        print(config_file)
Remove rogue print.

2023-10-11 16:00 UTC, CEgerer93 reviewed
Addressed/implemented comments on PR #256.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/geos_atmosphere.yaml
> +  letkf: fv3jedi_letkf.x
I agree - this would be consistent on both accounts.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  options:
Ideally no, the floats chosen for `local_ensemble_inflation_mult`, `local_ensemble_inflation_rtpp`, and `local_ensemble_inflation_rtps` would be left to the user to decide on.

I've removed the `options` for each, as the `default_value` sets values that appear standard.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  options:
Okay, this makes sense. I've moved `local_ensemble_save_posterior_ensemble{,_increments}` and `local_ensemble_save_posterior_mean{,_increment}` to the top-level `task_questions.yaml`.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  - true
Noted.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/deployment/prep_suite.py
> +        'RunJediLetkfExecutable',
Implemented this suggestion. I wonder about the "Local" aspect however, as EnKF, and I believe GETKF, don't compute local updates. I'll review those schemes, and potentially return to a better suite name.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/utilities/render_jedi_interface_files.py
> +        print(config_file)
Thanks. Done.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/tasks/run_jedi_letkf_executable.py
> +        # Ensemble Localizations
Done. I've changed the variable `jedi_application` to reflect this as well.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/tasks/task_questions.yaml
> +local_ensemble_inflation_mult:
Understood. Removed options from `local_ensemble_inflation_mult`, `local_ensemble_inflation_rtpp`, and `local_ensemble_inflation_rtps`.

2023-10-11 16:00 UTC, CEgerer93 commented on src/swell/tasks/task_questions.yaml
> +  options: defer_to_model
Set `local_ensemble_save_posterior_*` options at top-level - not deferred to model.

2023-10-11 16:34 UTC, danholdaway commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
> +  options:
I think you still want them here but they should be just:

```
local_ensemble_save_posterior_ensemble:
  default_value: true
```

I.e. without the options part. The options don't differ between models, they are always true or false regardless of model.

2023-10-11 17:54 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +  options: defer_to_model
```suggestion
```

2023-10-11 17:54 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +  options: defer_to_model
```suggestion
```

2023-10-11 17:56 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +  type: string
If you have a string with options can you select either `string-drop-list` or `string-check-list` depending on whether one or multiple choices are valid.

2023-10-11 17:57 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +  options: defer_to_model
```suggestion
```

2023-10-11 17:59 UTC, danholdaway commented on src/swell/utilities/run_jedi_executables.py
> +                        obsLocalize = []
I think this might add the `obs localizations` dictionary to the observations even when the applciation is not LocalEnsembleDa. I think you need to fence this somehow. A better thing might just be to add is in the RunJediLocalEnsembleDa task though, instead of here with an if statement.

2023-10-11 18:06 UTC, danholdaway commented
I sorted out the conflicts and have a few extra comments.

2023-10-11 19:57 UTC, CEgerer93 commented on src/swell/tasks/task_questions.yaml
> +  options: defer_to_model
Missed this mistaken deferral in `horizontal_localization_max_nobs` and `horizontal_localization_lengthscale` above - thanks.

2023-10-11 20:03 UTC, CEgerer93 commented on src/swell/tasks/task_questions.yaml
> +  type: string
I had left `type` as `string`, as Gaspari-Cohn is the only scheme currently supported for vertical localization. This will probably change, so I will change `type` to a `string-drop-list`.

2023-10-12 16:34 UTC, CEgerer93 commented on src/swell/utilities/run_jedi_executables.py
> +                        obsLocalize = []
Whoops, yes that would add localizations to observations for any task. I've removed the offending code block from `src/swell/utilities/run_jedi_executables.py` and adapted `src/swell/tasks/run_jedi_local_ensemble_da_executable.py` to accomplish the same behavior but for the `localensembleda` application only.

2023-10-12 16:52 UTC, CEgerer93 commented
Addressed suggestions - perhaps the most important being the relocation of obs localization block into `run_jedi_local_ensemble_da_executable.py`.

2023-10-18 14:30 UTC, danholdaway approved these changes
Thanks for working on this great new feature @CEgerer93.

2023-10-18 14:31 UTC, danholdaway commented
Just running the tier 1 tests to make sure there is no impact elsewhere https://github.com/GEOS-ESM/swell/actions/runs/6562412615

2023-10-18 19:38 UTC, merged