Feature/single obs test
GEOS-ESM/swell pull request #266
Opened 2023-10-18 13:49 UTC by gmao-jjin3

Add an option to make and test single-observation files. Those files are saved from the first data in radiance ioda files or un-combined conventional ioda files.  In other words , there are more than one observation in some combined conventional files, but they are different observations such as temperature, station pressure, specific humidity, and winds.

2023-10-18 13:53 UTC, gmao-jjin3 commented
I couldn't find the branch "feature/single_entry_point" which is the base of this PR.

2023-10-25 20:25 UTC, gmao-jjin3 commented
A new JEDI/UFO PR is made https://github.com/JCSDA-internal/ufo/pull/3082, and is needed in order to successfully conduct single-observation tests with multiple processors.

2023-10-27 17:14 UTC, danholdaway requested changes
One minor comment. THank you for adding this.

2023-10-27 17:14 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +  ask_question: true
Can you change this to false since we can consider it an advanced option and not something we want to ask users every time they are setting up an experiment.

2023-10-27 18:10 UTC, gmao-jjin3 commented on src/swell/tasks/task_questions.yaml
> +  ask_question: true
Done.  Should we use "single_observations" or "single_observation"?

2023-10-27 18:39 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +  ask_question: true
Probably doesn't matter too much.

2023-10-27 18:40 UTC, danholdaway approved these changes

2023-10-27 18:40 UTC, merged