Accessing GSI observing system records for active and available channels
GEOS-ESM/swell pull request #273
Opened 2023-10-30 19:37 UTC by asewnath

## Description

Initial PR making changes required to update yaml use flags during cylc workflow run. PR does the following:
- Change amsua_n19.yaml to include active channel jinja templating in `use_flag` field
- Adding two new tasks: `CloneGeosAna` and `GenerateObservingSystemRecords`
- Created new object `ObservingSystemRecords` to handle parsing active and available channel tables from GSI
- Modified `render_interface_observation` function to call new `get_active_channels` function. 
- Modifying relevant tasks to get `observing_system_record_path` for `render_interface_observation` or `jedi_dictionary_iterator` function

Changes that still need to be made: (can be in this PR or another one)
- Update all yaml files with use_flag field to have active channel jinja templating
- Available channels jinja templating in all yaml files
- Add logger into functions for proper aborts

2023-10-31 01:57 UTC, danholdaway requested changes
Thank you very much for adding this very important functionality @asewnath. I just have a few minor comments about code readability. The overall functionality looks great.

The only other comment I would make is in having these three files: `sat_db_utils`, `instr_state_machine` and `observing_system_records`. Do we still need all three? What is the difference between what's in the files? It's not very easy to tell by the names of the files.

2023-10-31 01:57 UTC, danholdaway commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/observations/amsua_n19.yaml
> +        #use_flag: [-1, -1, -1,  1,  1,
Can you remove the comments? Below as well.

2023-10-31 01:57 UTC, danholdaway commented on src/swell/suites/ufo_testing/flow.cylc
> +            #GenerateObservingSystemRecords
Delete this commented line

2023-10-31 01:57 UTC, danholdaway commented on src/swell/suites/ufo_testing/flow.cylc
> +        script = "swell task CloneGeosAna $config -d $datetime -m geos_atmosphere"
Can you remove the -d and -m arguments from this call. The tasks should not depend of either.

2023-10-31 01:57 UTC, danholdaway commented on src/swell/tasks/base/task_registry.py
> +# (C) Copyright 2021- United States Government as represented by the Administrator of the
I thought this file got removed?

2023-10-31 01:57 UTC, danholdaway commented on src/swell/tasks/gsi_bc_to_ioda.py
> +        cycle_time = os.path.normpath(cycle_dir).split('/')[-2]
There should be a `self.cycle_time_dto()` and `self.cycle_time()`. Please use one of these instead.

2023-10-31 01:57 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +observing_system_records_gsi_path:
Can you add a:

```
models:
- all
```

2023-10-31 01:57 UTC, danholdaway commented on src/swell/tasks/task_questions.yaml
> +observing_system_records_gsi_path:
And below

2023-10-31 01:57 UTC, danholdaway commented on src/swell/test/code_tests/generate_observing_system_test.py
> +path_to_geosana_gridcomp = '/discover/nobackup/asewnath/github/GEOSana_GridComp/'
Ideally a unit test should be able to run regardless of where it is run, for example if we want to run it on GitHub. Is there a way of doing this without the absolute path to something in your space?

2023-10-31 01:57 UTC, danholdaway commented on src/swell/utilities/render_jedi_interface_files.py
> +    def render_interface_observations(self, config_name, path_to_observing_sys_yamls, cycle_time):
Instead of passing cycle_time to this method each time can you pass it to the constructor along side cycle_dir?

2023-10-31 01:57 UTC, danholdaway commented on src/swell/utilities/render_jedi_interface_files.py
> +    def render_interface_ufo_test(self):
Why was a specific function for ufo_tests needed?

2023-10-31 01:57 UTC, danholdaway commented on src/swell/utilities/run_jedi_executables.py
> +                            observing_system_records_path,
Because of this being called recursively and from multiple places...what about adding a method to `jedi_rendering` called `set_observing_system_records_path`? Then you don't have to change the interface to this method. You could just add a check internally to `render_interface_observations` that makes sure the variable was set. This way if there are (in the future) calls to run_jedi_executable that doesn't involve observation we wont end up asking a question about the this path. It would avoid making any changes to the `jedi_dictionary_iterator` API.

2023-10-31 14:55 UTC, asewnath commented
> Thank you very much for adding this very important functionality @asewnath. I just have a few minor comments about code readability. The overall functionality looks great.
> 
> The only other comment I would make is in having these three files: `sat_db_utils`, `instr_state_machine` and `observing_system_records`. Do we still need all three? What is the difference between what's in the files? It's not very easy to tell by the names of the files.

The `observing_system_records` file contains the ObservingSystemRecords object, which has methods to parse the GSI records and save the yaml files.`instr_state_machine` is an old name that can be changed to something like `gsi_tbl_parser`. It contains the code that actually parses the GSI records. Since it's a lot of code, it seems cleaner to have it in a separate file. The `sat_db_utils` file contains different utilities for the channel update process. `read_sat_db` is used only by `ObservingSystemRecords` and can be moved to `observing_system_records`. `run_sat_db_process` is legacy code that can be deleted. Then there are functions that are used for the channel update that are not associated with the `ObservingSystemRecords` object. This includes `get_active_channels` and other functions necessary for the active channel retrieval. A separate file seems appropriate for these functions, and the file itself can be changed to `get_active_channels` or something along those lines. I can also add more documentation to all these files.

2023-10-31 15:42 UTC, danholdaway commented
> > Thank you very much for adding this very important functionality @asewnath. I just have a few minor comments about code readability. The overall functionality looks great.
> > The only other comment I would make is in having these three files: `sat_db_utils`, `instr_state_machine` and `observing_system_records`. Do we still need all three? What is the difference between what's in the files? It's not very easy to tell by the names of the files.
> 
> The `observing_system_records` file contains the `ObservingSystemRecords` object, which has methods to parse the GSI records and save the yaml files.`instr_state_machine` is an old name that can be changed to something like `gsi_tbl_parser`. It contains the code that actually parses the GSI records. Since it's a lot of code, it seems cleaner to have it in a separate file. The `sat_db_utils` file contains different utilities for the channel update process. `read_sat_db` is used only by `ObservingSystemRecords` and can be moved to `observing_system_records`. `run_sat_db_process` is legacy code that can be deleted. The only place it is called in is `utilities/scripts/swell_sat_db_processing.py`, which can also be deleted. Then there are functions that are used for the channel update that are not associated with the `ObservingSystemRecords` object. This includes `get_active_channels` and other functions necessary for the active channel retrieval. A separate file seems appropriate for these functions, and the file itself can be changed to `get_active_channels` or something along those lines. I can also add more documentation to all these files.

Thanks for the explanation. I think some renaming and clean up of any unused code should be sufficient.

2023-10-31 18:49 UTC, asewnath commented on src/swell/utilities/run_jedi_executables.py
> +                            observing_system_records_path,
I'll also do this to set the cycle time so that `render_interface_observations` can go back to passing in just `config_name`

2023-10-31 19:46 UTC, danholdaway commented on src/swell/utilities/run_jedi_executables.py
> +                            observing_system_records_path,
Sounds good.

2023-10-31 22:13 UTC, asewnath commented on src/swell/utilities/render_jedi_interface_files.py
> +    def render_interface_observations(self, config_name, path_to_observing_sys_yamls, cycle_time):
Ah, missed that you already talked about passing cycle_time to the constructor earlier!

2023-11-15 21:03 UTC, danholdaway approved these changes

2023-11-15 21:03 UTC, merged