Add task to calculate ensemble mean and variance from background state
GEOS-ESM/swell pull request #397
Opened 2024-07-31 04:20 UTC by metdyn

## Description

A step towards LETKF is to calculate ensemble mean and variance:
- https://github.com/GEOS-ESM/swell/issues/365

Alternatively, this functionality may be used as a simple, independent tool.

Tested on SCU17:
```
swell create localensembleda  -s slurmfile.yaml -p nccs_discover_sles15

slurm_directives_tasks:
  RunJediLocalEnsembleDaExecutable:
    geos_atmosphere:
      nodes: 1
      ntasks-per-node: 36
  GetEnsembleMeanVariance:
    all:
      nodes: 1
      ntasks-per-node: 36
```

## Dependencies

None

## Impact

It is part of the localensembleda suite.

2024-07-31 17:43 UTC, rtodling commented
This seems to work - it runs fine, but I am confused as to what's preventing the localensembleda to go beyond simply  the ensemean background ... after all, this is behaving as if it were the ensemblemean suite but it's not!

2024-08-01 15:43 UTC, Dooruk commented
@rtodling and @metdyn this is missing the last commit from the `develop` branch.

Please see following changes. We are abandoning the static `StageJedi` task to be able to use relative paths and run `StageJediCycle` at each cycle, which puts static files in the `{cycle_dir}`: 

https://github.com/GEOS-ESM/swell/compare/feature/submit/ens_mean...develop

@metdyn, please notice the changes in `flow.cylc` for `3dvar_atmos` and `3dfgat_atmos`, they need to be replicated for the `localensembleda` suite.

2024-08-01 15:58 UTC, metdyn commented
> @rtodling and @metdyn this is missing the last commit from the `develop` branch.
> 
> Please see following changes. We are abandoning the static `StageJedi` task to be able to use relative paths and instead running `StageJediCycle` at each cycle, which puts static files in the `{cycle_dir}`:
> 
> [feature/submit/ens_mean...develop](https://github.com/GEOS-ESM/swell/compare/feature/submit/ens_mean...develop)
> 
> @metdyn, please notice the changes in `flow.cylc` for `3dvar_atmos` and `3dfgat_atmos`, they need to be replicated for the `localensembleda` suite.

Thanks, @Dooruk, I will take a look and make appropriate changes to the PR to be update with other suites and relative path.

2024-08-02 18:02 UTC, metdyn commented
Hi @Dooruk @asewnath,

I know the ctest `swell test  code_tests` fails at 
https://github.com/GEOS-ESM/swell/blob/develop/src/swell/utilities/scripts/task_question_dicts.py#L134-L135

Error message is
```
FAIL: test_dictionary_comparison (swell.test.code_tests.question_dictionary_comparison_test.QuestionDictionaryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gpfsm/dnb07/projects/p234/yyu11/br_jedi_scu17/install_swell/src/swell/swell_ens_mean/src/swell/test/code_tests/question_dictionary_comparison_test.py", line 26, in test_dictionary_comparison
    assert tq_dicts_rc == 0
AssertionError
```

So I printed out the string of the dict into files:
```
yaml.dump(question_dict_str_in)
yaml.dump(dict_to_write_str)
```

diff diff in.txt   out.txt

Then I print out the first two lines of differences of the two files:

```
7,25c7,24
<   \ are the analysis variables?\n  tasks:\n  - GenerateBClimatology\n  - PrepareAnalysis\n\
<   \  - RunJediConvertStateSoca2ciceExecutable\n  - RunJediVariationalExecutable\n\
  \  - GetEnsembleMeanVariance\n  type: string-check-list\n\nbackground_error_model:\n\

---
>   \ are the analysis variables?\n  tasks:\n  - GenerateBClimatology\n  - GetEnsembleMeanVariance\n\
>   \  - PrepareAnalysis\n  - RunJediConvertStateSoca2ciceExecutable\n  - RunJediVariationalExecutable\n\
  \  type: string-check-list\n\nbackground_error_model:\n  ask_question: false\n \
```

The order between `GetEnsembleMeanVariance` and `PrepareAnalysis` is swap. 
So the dictionary comparison using the print out string becomes a problem when new tasks is added into task dir,
which changed glob.glob file list.
There should be a better way for the task questions yaml comparison.

<img width="935" alt="Screenshot 2024-08-02 at 11 49 19 AM" src="https://github.com/user-attachments/assets/93b5bf2a-5128-46f1-830d-799aa913f051">


Meanwhile I tried to print out the difference between the two dictionaries:
> set1 = set(dict1.items())
> set2 = set(dict2.items())
> set1 ^ set2
(https://stackoverflow.com/questions/32815640/how-to-get-the-difference-between-two-dictionaries-in-python)
There comes an error that the dictionary is not hashable.  I did not go further.

2024-08-02 18:10 UTC, metdyn commented
I think this error means I need to regenerate `tasks/task_questions.yaml`, because new tasks are added in. 
In this logic, then the test_dictionary_comparison function would be a good place as a generator.  Or I would manually check tasks/task_questions.yaml.  How was this done before?

2024-08-02 18:28 UTC, Dooruk commented
@metdyn, let me look into this branch and see what is going on. I will suggest an update to this branch afterwards as a merge. It's a simple unit test issue but I also notice some potential `Stage` task problems. 

If you change this following line in the source code (setting `$LOG_INFO` to 1 in the environment didn't work for me) and build it again, tests will provide more details to show you a temporary YAML file with the proper `task_questions.yaml`.
https://github.com/GEOS-ESM/swell/blob/465990f83f167f6820a4994d1af407804823d0f2/src/swell/test/code_tests/code_tests.py#L28-L29

Sorry, this is all very obscure without documentation but this is also how I learned these things..

2024-08-02 18:53 UTC, metdyn commented
@Dooruk thanks and that is the key! I was about to ask you why the logger.info did not work in this test code file, but logger.test() worked in another file.

2024-08-06 17:37 UTC, Dooruk commented
@rtodling, can you confirm `RunJediEnsembleMeanVariance` works on your end so we can merge this?

2024-08-06 17:47 UTC, Dooruk requested changes
I added a few comments. There is some duplicate functionality because `RunJediEnsembleMean` already handles the options where you put inside `RunJediLocalDaExecutable`. Simply taking them out should suffice.

2024-08-06 17:47 UTC, Dooruk commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +        jedi_ensmeanvariance_application = 'ensmeanvariance'
Is this still necessary after `RunJediEnsembleMean` task is implemented?

2024-08-06 17:47 UTC, Dooruk commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +        ensmeanvariance_only = self.config.ensmeanvariance_only()
Same comment regarding `RunJediEnsembleMean`

2024-08-06 17:47 UTC, Dooruk commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +                                    self.config.ensmeanvariance_only())
same ^ `RunJediEnsembleMean`

2024-08-06 17:47 UTC, Dooruk commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +                               jedi_config_file, output_log_file)
Same comment regarding `RunJediEnsembleMean` ^

2024-08-06 17:47 UTC, Dooruk commented on src/swell/tasks/task_questions.yaml
> +
same ^

2024-08-06 17:47 UTC, Dooruk commented on src/swell/test/suite_tests/localensembleda-tier1.yaml
> +#    - T18
You could keep the `cycle_times` uncommented but keep a single `start_cycle_time` and `end_cycle_time` so T06, T12, and T18 won't be triggered.

2024-08-06 17:47 UTC, Dooruk commented on src/swell/utilities/render_jedi_interface_files.py
> +            'ensmeanvariance_only',
same^

2024-08-06 17:47 UTC, Dooruk commented on .gitignore
> +.#*
Why were these changed?

`._*` are Mac temporary files.

2024-08-06 22:18 UTC, metdyn commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +        jedi_ensmeanvariance_application = 'ensmeanvariance'
The `RunJediEnsembleMean` is an external test.  This statement is a separate one that can be used after LETKF run.

2024-08-06 22:22 UTC, metdyn commented on .gitignore
> +.#*
These are modified file copies left by Emacs

2024-08-07 06:37 UTC, metdyn commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +        ensmeanvariance_only = self.config.ensmeanvariance_only()
same as above, to compute mean and variance at the end of this code.

2024-08-07 06:39 UTC, metdyn commented on src/swell/tasks/task_questions.yaml
> +
If we donot need it later on, we will remove it.

2024-08-07 06:49 UTC, metdyn reviewed
I created another PR to help with enHX with packets. 
https://github.com/GEOS-ESM/swell/pull/405

2024-08-07 06:49 UTC, metdyn commented on src/swell/test/suite_tests/localensembleda-tier1.yaml
> +#    - T18
Thanks, that will also work!  I have changed the T06,12,18 back.

2024-08-07 18:07 UTC, Dooruk commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +        jedi_ensmeanvariance_application = 'ensmeanvariance'
Ok thanks, this is now clear to me after today's meeting.

2024-08-07 18:08 UTC, Dooruk approved these changes
This is good to go on my end, let's wait on @rtodling .

2024-08-08 17:21 UTC, rtodling approved these changes
This works for me - it fails in the HofX, but I understand this is another issue to be tackled elsewhere.

2024-08-08 17:22 UTC, merged