Type hinting and misc changes
GEOS-ESM/swell pull request #417
Opened 2024-09-11 22:40 UTC by mranst

## Description

Adds type hinting for all python modules (#349)
 - renamed datetime.py to datetime_util.py to avoid confusion with baseline package
 -  -  - 
SLES15 is now default platform (#407) 
 - updated docs to reflect this, along with a few additions which may help new users
 -  -  - 
If specified in config and a valid location, appropriate tasks will now source from swell_static_files_user (#360)
 - GenerateBCClimatology
 - StageJedi 
 -  GetGeosRestart 
 - PrepGeosRunDir
 -  -  -  

Addressed a potential error when trying to abort in observing_system_records.py

2024-09-13 14:14 UTC, asewnath reviewed
@mranst Thanks for all of these type hint changes and catches

2024-09-13 14:14 UTC, asewnath commented on src/swell/deployment/create_experiment.py
> +    logger: Logger,
`Logger` isn't used in this function so I'm wondering why we are passing it in.

2024-09-13 14:14 UTC, asewnath commented on src/swell/deployment/create_experiment.py
> +    logger: 'Logger',
`logger` type is the class `Logger`, again I'm wondering why we are passing this in if not used.

2024-09-13 14:14 UTC, asewnath commented on src/swell/tasks/run_geos_executable.py
> +        geos_lib_path: Union[str, None] = None
This type hint can also be `Optional[str]`

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/data_assimilation_window_params.py
> +    def __init__(self, logger: 'Logger', cycle_time: str) -> None:
`logger` is `Logger` class, need to import `Logger` as well

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/exceptions.py
> +        logger: Union['Logger', None] = None
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/file_system_operations.py
> +def copy_to_dst_dir(logger: 'Logger', src: str, dst_dir: str) -> None:
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/file_system_operations.py
> +        logger: 'Logger',
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/file_system_operations.py
> +def check_if_files_exist_in_path(logger: 'Logger', path_to_files: str) -> bool:
`Logger` class for type hint

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/file_system_operations.py
> +    logger: 'Logger',
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/geos.py
> +    def __init__(self, logger: 'Logger', forecast_dir: str) -> None:
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/get_channels.py
> +    logger: 'Logger'
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/git_utils.py
> +def git_change_branch(logger: 'Logger', git_branch: str, out_dir: str) -> None:
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/gsi_record_parser.py
> +    def run(self, instr_df: pd.core.frame.DataFrame) -> None:
Why is this `pd.core.frame.DataFrame` instead of `pd.DataFrame`? Just curious

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/jinja2.py
> +    def __getattr__(self, name: str) -> 'SilentUndefined':
Return type is `SilentUndefined` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/observations.py
> +def ioda_name_to_long_name(ioda_name: str, logger: 'Logger') -> str:
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/observing_system_records.py
> +            self.logger.abort(f'Record type {self.record_type} not supported. \
Fantastic catch, thank you!

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/render_jedi_interface_files.py
> +        logger: 'Logger',
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/render_jedi_interface_files.py
> +    def render_interface_meta(self, model_component_in: Union[str, dict] = None) -> dict:
If `model_component_in` is set to `None` by default, then it's type needs to also include `None`

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/run_jedi_executables.py
> +    logger: 'Logger',
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/scripts/task_question_dicts_defaults.py
> +    logger: 'Logger',
`Logger` class

2024-09-13 14:14 UTC, asewnath commented on src/swell/utilities/shell_commands.py
> +    logger: 'Logger',
`Logger` class

2024-09-13 15:14 UTC, ashiklom requested changes
Excellent work! I just had a few minor suggestions, but overall, this is well done. Having type hints everywhere will be a huge quality of life improvement for Swell developers, especially around some of our weirder functions.

Did you also try running Swell through a static type checker like mypy or Pyright?

2024-09-13 15:14 UTC, ashiklom commented on docs/configuring_cylc.md
> +See `docs/platforms/configuring_cylc_discover.md` for instructions on configuring cylc for Discover.
Better to make this an actual link, via synax like this (note: links are relative to the `docs` folder, not the Swell root).

```suggestion
See [Configuring Cylc Discover](platforms/configuring_cylc_discover.md) for instructions on configuring cylc for Discover.
```

2024-09-13 15:14 UTC, ashiklom commented on src/swell/deployment/create_experiment.py
> +    logger: 'Logger',
Why a string here rather than the `Logger` object?

```suggestion
    logger: Logger,
```

2024-09-13 15:14 UTC, ashiklom commented on src/swell/deployment/prepare_config_and_suite/question_and_answer_defaults.py
> +    def get_answer(self, key: str, val: dict) -> str:
Are we sure the result is always a string here? Don't we have some numeric, datetime, etc. values?

2024-09-13 15:14 UTC, ashiklom commented on src/swell/swell.py
> +def t1test(suite: str) -> None:
We can actually be even stricter with the type hinting here by restricting to specific values, which helps catch a higher level of bug (and provides even better inline documentation):

```suggestion
def t1test(suite: Literal["hofx", "3dvar", "ufo_testing"]) -> None:
```

(Requires `from typing import Literal` above)

2024-09-13 15:14 UTC, ashiklom commented on src/swell/tasks/base/task_base.py
> +        datetime: Union[str, None],
We're sure these have to be strings and can't be `datetime` objects?

2024-09-13 15:14 UTC, ashiklom commented on src/swell/tasks/base/task_base.py
> +    datetime: Union[str, None],
Ditto above --- this definitely can't be a `datetime` object?

2024-09-13 15:14 UTC, ashiklom commented on src/swell/test/code_tests/slurm_test.py
> +    def test_slurm_config(self, platform_mocked: dict, mock_global_defaults: dict) -> None:
Is `dict` the right annotation here? I think what these should really be is probably `unittest.mock.Mock`:

```suggestion
    def test_slurm_config(self, platform_mocked: Mock, mock_global_defaults: Mock) -> None:
```

Note that this requires `from unittest.mock import Mock` above. Or, you can use a forward reference -- `: "Mock"`.

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/data_assimilation_window_params.py
> +    def __get_window_begin_dto__(self, window_offset: str) -> datetime:
`datetime` is the module; the class is `datetime.datetime`.

```suggestion
    def __get_window_begin_dto__(self, window_offset: str) -> datetime.datetime:
```

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/data_assimilation_window_params.py
> +    def __get_local_background_time__(self, window_type: str, window_offset: str) -> datetime:
Ditto.
```suggestion
    def __get_local_background_time__(self, window_type: str, window_offset: str) -> datetime.datetime:
```

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/filehandler.py
> +def get_file_handler(config: list, **kwargs) -> Union['StageFileHandler', 'GetDataFileHandler']:
Forward references for "Logger" are fine because that's fairly obvious. However, for more specialized Swell-specific classes like this, I might recommend actually importing the classes (if necessary) and referring to them directly here. That will make it easier for people to see exactly where these classes are defined (e.g., using a "go to definition" function in modern text editors).

```python
def get_file_handler(config: list, **kwargs) -> Union[StageFileHandler, GetDataFileHandler]:
```

Or does this fail because the classes are defined lower in the file?

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/filehandler.py
> +    def is_ready(self, fc: Union['FileCollection', None] = None) -> bool:
Ditto to above.

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/filehandler.py
> +    def get(self, fc: Union['FileCollection', None] = None) -> None:
Ditto to above.

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/gsi_record_parser.py
> +    def run(self, instr_df: pd.core.frame.DataFrame) -> None:
Does this not work?

```suggestion
    def run(self, instr_df: pd.DataFrame) -> None:
```

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/jinja2.py
> +    def __getattr__(self, name: str) -> 'SilentUndefined':
For my own understanding: Do these need to be Forward References (i.e., in quotes) for this to work, to prevent some kind of circular dependency error?

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/gsi_record_parser.py
> +    def get_instr_df(self) -> pd.core.frame.DataFrame:
Ditto here.

2024-09-13 15:14 UTC, ashiklom commented on src/swell/utilities/observing_system_records.py
> +def read_sat_db(path_to_sat_db: str, column_names: list) -> pd.core.frame.DataFrame:
Ditto - `pd.DataFrame`

2024-09-13 15:17 UTC, ashiklom commented on src/swell/utilities/data_assimilation_window_params.py
> +    def __init__(self, logger: 'Logger', cycle_time: str) -> None:
This is actually a correct type hint, called a [Forward Reference](https://peps.python.org/pep-0484/#forward-references). It's a way to annotate types without being forced to import the underlying class. They are also useful in situations where having to import the underlying class would result in weird circular import errors (which is not the case here).

See my comment below about this. In general, I think using Forward References like this for the `Logger` class is OK because (1) it's relatively obvious where the Logger class is in our code; and (2) I think we're basically consistent with Python's standard library Logger interface anyway (`logging.Logger`), so the classes are interchangeable.

2024-09-13 15:22 UTC, Dooruk requested changes
Thank you, this is colossal work @mranst! Just a few minor comments following others.

I made a copy of your branch to run Tier1 tests (which they run succesfully)

https://github.com/GEOS-ESM/swell/actions/runs/10850825590

Are you part of GEOS-ESM and push changes to and create branches on Swell repo? I think we need to add you.

2024-09-13 15:22 UTC, Dooruk commented on src/swell/utilities/shell_commands.py
> +    logger: 'Logger',
To add more Logger classes following @asewnath's comments

2024-09-13 15:22 UTC, Dooruk commented on src/swell/utilities/shell_commands.py
> +    logger: 'Logger',
Logger class

2024-09-13 15:22 UTC, Dooruk commented on src/swell/utilities/scripts/task_question_dicts_defaults.py
> +    logger: 'Logger',
Logger class

2024-09-13 15:22 UTC, Dooruk commented on src/swell/utilities/run_jedi_executables.py
> +    jedi_rendering,
Just curious, for typehinting purposes would this be empty, @asewnath or @ashiklom?

This is where `jedi_rendering` is created:

https://github.com/GEOS-ESM/swell/blob/2649e973c246d86898f1c7df713c28e50cad29ce/src/swell/tasks/base/task_base.py#L96-L98

2024-09-13 15:22 UTC, Dooruk commented on src/swell/utilities/dictionary.py
> +def dictionary_override(logger: 'Logger', orig_dict: dict, override_dict: dict) -> dict:
Logger class

2024-09-13 15:22 UTC, Dooruk commented on src/swell/utilities/dictionary.py
> +    logger: 'Logger',
Logger class

2024-09-13 15:22 UTC, Dooruk commented on src/swell/utilities/dictionary.py
> +    logger: 'Logger',
Logger class

2024-09-13 15:38 UTC, ashiklom commented on src/swell/utilities/run_jedi_executables.py
> +    jedi_rendering,
I'm guessing Michael just missed this one. Based on your comment, I'm guessing it should be something like:

```python
from swell.tasks.base.task_base import JediConfigRendering
# [...]
def jedi_dictionary_iterator(
  #...
  jedi_rendering: JediConfigRendering
  # ...
) #...
```

2024-09-13 15:43 UTC, ashiklom commented
@asewnath @Dooruk Thanks both for the thorough reviews!

We should probably come to some consensus on the use of [Forward References](https://peps.python.org/pep-0484/#forward-references) in type hints (i.e., `logger: "Logger"`) vs. direct class references (`from swell.logger import Logger; logger: Logger`), so @mranst can just resolve all of those without our individual approval.

I don't have very strong feelings about this. My mild preference is:

1. Accept Forward References for "Logger" because it's relatively obvious what that is and where it comes from (and, I think our Logger class should be more-or-less interchangeable with the `logging.Logger` from the Python standard library), but...
2. Prefer direct class references + imports for more specialized classes (e.g., `FileCollection`, `JediConfigRendering`) so that it's easier for future developers to jump to those definitions.

What do you two think?

2024-09-13 15:53 UTC, mranst commented
Thanks for the comments everyone! I have added direct type hinting for Logger everywhere, unless we do want to go back to the forward references. I'm looking through for other object instance calls so I can type them directly, as well.

2024-09-13 17:41 UTC, mranst commented on src/swell/deployment/create_experiment.py
> +    logger: Logger,
Removed both unused passes to Logger

2024-09-13 17:41 UTC, mranst commented on src/swell/deployment/create_experiment.py
> +    logger: 'Logger',
Removed both unused passes to Logger

2024-09-13 17:42 UTC, mranst commented on src/swell/tasks/run_geos_executable.py
> +        geos_lib_path: Union[str, None] = None
instances of this type of hint have been changed where appropriate

2024-09-13 17:43 UTC, mranst commented on src/swell/utilities/data_assimilation_window_params.py
> +    def __init__(self, logger: 'Logger', cycle_time: str) -> None:
I've changed type hinting for Logger throughout, it is now directly references

2024-09-13 17:47 UTC, mranst commented on src/swell/utilities/jinja2.py
> +    def __getattr__(self, name: str) -> 'SilentUndefined':
SilentUndefined is now directly referenced, since this is a hint to the enclosing class I used `from __future__ import annotations`

2024-09-13 17:48 UTC, mranst commented on src/swell/utilities/render_jedi_interface_files.py
> +    def render_interface_meta(self, model_component_in: Union[str, dict] = None) -> dict:
Resolved, thanks!

2024-09-13 17:51 UTC, mranst commented on src/swell/utilities/gsi_record_parser.py
> +    def run(self, instr_df: pd.core.frame.DataFrame) -> None:
When I ran type() on a dataframe, this is what it returned. I believe both are correct for type hinting so I've changed it to `pd.DataFrame` for simplicity

2024-09-13 18:42 UTC, mranst commented on src/swell/deployment/create_experiment.py
> +    logger: 'Logger',
No reason other than that I was in the habit of it, I've changed this and all other forward references to Logger.

2024-09-13 19:35 UTC, mranst commented on src/swell/deployment/prepare_config_and_suite/question_and_answer_defaults.py
> +    def get_answer(self, key: str, val: dict) -> str:
I wasn't sure which types were possible, I've included the possibility for  `int`, `float`, and `datetime`, although it should maybe be even more generic than that

2024-09-13 19:35 UTC, mranst commented on src/swell/swell.py
> +def t1test(suite: str) -> None:
Changed!

2024-09-13 19:37 UTC, mranst commented on src/swell/tasks/base/task_base.py
> +        datetime: Union[str, None],
At the time, I thought that the value was coming directly from the command line so I assumed it was a string, but I've added datetime as a type

2024-09-13 19:37 UTC, mranst commented on src/swell/test/code_tests/slurm_test.py
> +    def test_slurm_config(self, platform_mocked: dict, mock_global_defaults: dict) -> None:
I've added a direct hint to Mock

2024-09-13 19:41 UTC, mranst commented on src/swell/utilities/filehandler.py
> +def get_file_handler(config: list, **kwargs) -> Union['StageFileHandler', 'GetDataFileHandler']:
To my knowledge it will fail natively unless you have `from __future__ import annotations` at the top of the file. I have included this so we can directly hint to it, although I believe this will not work in Python<3.7 (not sure if that matters)

2024-09-13 19:45 UTC, mranst commented on src/swell/utilities/jinja2.py
> +    def __getattr__(self, name: str) -> 'SilentUndefined':
Like above, if you include `from __future__ import annotations` you can reference a class instance within itself without error

2024-09-13 19:46 UTC, mranst commented on src/swell/utilities/shell_commands.py
> +    logger: 'Logger',
I've changed all forward reference to Logger to direct references

2024-09-13 19:49 UTC, mranst commented on src/swell/utilities/run_jedi_executables.py
> +    jedi_rendering,
I missed this one before, I've made this change

2024-09-13 20:23 UTC, asewnath commented on src/swell/utilities/data_assimilation_window_params.py
> +    def __init__(self, logger: 'Logger', cycle_time: str) -> None:
@ashiklom Thanks Alexey, good to know

2024-09-13 20:33 UTC, asewnath commented
> What do you two think?

@ashiklom I'm inclined to sticking with direct class references for now. Seeing both forward references and direct class references may be confusing for new users and developers. If we wanted to use both approaches, we should document our type hinting methodology for clarification.

2024-09-16 13:50 UTC, Dooruk commented
> > What do you two think?
> 
> @ashiklom I'm inclined to sticking with direct class references for now. Seeing both forward references and direct class references may be confusing for new users and developers. If we wanted to use both approaches, we should document our type hinting methodology for clarification.

I agree with @asewnath on this one. I think many Python users (myself included) aren't familiar with typehinting and forward refence is one step beyond that. Direct class reference is more straightforward.

2024-09-16 13:51 UTC, Dooruk approved these changes, later dismissed
This is all good, thanks again @mranst! I will wait on others approval before merging.

2024-09-16 14:33 UTC, ashiklom reviewed
Changes look good! However, when I ran this through a type checker locally (`mypy`), it turned up a bunch of errors. We don't have to address all (or even most, and perhaps not any) of them now...but I recommend taking a look through this list and deciding consciously which of the errors are worth fixing now and which ones we can wait on for a future PR.

@mranst I leave this up to your judgment. Let me know when you think we've hit a reasonably stopping point for this PR.

Full `mypy` output is in the Details below.

<details>

```
src/swell/deployment/platforms/platforms.py:12: error: Library stubs not installed for "yaml"  [import-untyped]
src/swell/deployment/platforms/platforms.py:12: note: Hint: "python3 -m pip install types-PyYAML"
src/swell/deployment/platforms/platforms.py:12: note: (or run "mypy --install-types" to install all missing stub packages)
src/swell/deployment/platforms/platforms.py:12: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/swell/utilities/slurm.py:13: error: Library stubs not installed for "yaml"  [import-untyped]
src/swell/utilities/slurm.py:201: error: Item "None" of "Match[str] | None" has no attribute "group"  [union-attr]
src/swell/utilities/shell_commands.py:39: error: Item "None" of "IO[bytes] | None" has no attribute "readline"  [union-attr]
src/swell/utilities/shell_commands.py:71: error: Argument "stdout" to "run_subprocess" has incompatible type "int"; expected "str | None"  [arg-type]
src/swell/utilities/shell_commands.py:71: error: Argument "stderr" to "run_subprocess" has incompatible type "int"; expected "str | None"  [arg-type]
src/swell/utilities/shell_commands.py:86: error: Argument "stdout" to "run" has incompatible type "str | None"; expected "int | IO[Any] | None"  [arg-type]
src/swell/utilities/shell_commands.py:86: error: Argument "stderr" to "run" has incompatible type "str | None"; expected "int | IO[Any] | None"  [arg-type]
src/swell/utilities/observations.py:11: error: Library stubs not installed for "yaml"  [import-untyped]
src/swell/utilities/netcdf_files.py:12: error: Cannot find implementation or library stub for module named "xarray"  [import-not-found]
src/swell/utilities/get_channels.py:10: error: Library stubs not installed for "yaml"  [import-untyped]
src/swell/utilities/get_channels.py:54: error: Incompatible return value type (got "str", expected "list[Any]")  [return-value]
src/swell/utilities/get_channels.py:59: error: Missing return statement  [return]
src/swell/utilities/get_channels.py:110: error: Incompatible return value type (got "tuple[list[Any], list[int]]", expected "tuple[str, list[Any]]")  [return-value]
src/swell/utilities/get_channels.py:113: error: Incompatible return value type (got "tuple[None, None]", expected "tuple[str, list[Any]]")  [return-value]
src/swell/utilities/get_channels.py:134: error: No return value expected  [return-value]
src/swell/utilities/exceptions.py:25: error: "Logger" not callable  [operator]
src/swell/utilities/dictionary.py:10: error: Library stubs not installed for "yaml"  [import-untyped]
src/swell/utilities/dictionary.py:19: error: Missing return statement  [return]
src/swell/utilities/config.py:11: error: Library stubs not installed for "yaml"  [import-untyped]
src/swell/utilities/config.py:68: error: Incompatible types in assignment (expression has type "None", variable has type "list[Any]")  [assignment]
src/swell/utilities/scripts/check_jedi_interface_templates.py:71: error: Need type annotation for "templates" (hint: "templates: list[<type>] = ...")  [var-annotated]
src/swell/utilities/git_utils.py:28: error: Argument 2 to "run_subprocess_dev_null" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/utilities/git_utils.py:51: error: Argument 2 to "run_subprocess_dev_null" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/utilities/git_utils.py:75: error: Argument 2 to "run_subprocess_dev_null" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/utilities/git_utils.py:85: error: Argument 2 to "run_subprocess_dev_null" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/utilities/geos.py:11: error: Skipping analyzing "f90nml": module is installed, but missing library stubs or py.typed marker  [import-untyped]
src/swell/utilities/geos.py:13: error: Skipping analyzing "isodate": module is installed, but missing library stubs or py.typed marker  [import-untyped]
src/swell/utilities/geos.py:14: error: Skipping analyzing "netCDF4": module is installed, but missing library stubs or py.typed marker  [import-untyped]
src/swell/utilities/geos.py:110: error: Argument 2 to "run_subprocess" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/utilities/geos.py:172: error: Incompatible default for argument "dst_dir" (default has type "None", argument has type "str")  [assignment]
src/swell/utilities/geos.py:172: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
src/swell/utilities/geos.py:172: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
src/swell/utilities/geos.py:279: error: Incompatible types in assignment (expression has type "list[str]", variable has type "str")  [assignment]
src/swell/utilities/data_assimilation_window_params.py:11: error: Skipping analyzing "isodate": module is installed, but missing library stubs or py.typed marker  [import-untyped]
src/swell/utilities/data_assimilation_window_params.py:66: error: Incompatible return value type (got "datetime", expected "str")  [return-value]
src/swell/test/code_tests/slurm_test.py:54: error: Argument 1 to "prepare_scheduling_dict" has incompatible type "logging.Logger"; expected "swell.utilities.logger.Logger"  [arg-type]
src/swell/test/code_tests/slurm_test.py:60: error: Argument 1 to "prepare_scheduling_dict" has incompatible type "logging.Logger"; expected "swell.utilities.logger.Logger"  [arg-type]
src/swell/test/code_tests/slurm_test.py:68: error: Argument 1 to "prepare_scheduling_dict" has incompatible type "logging.Logger"; expected "swell.utilities.logger.Logger"  [arg-type]
src/swell/deployment/launch_experiment.py:58: error: Argument 2 to "run_subprocess" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/deployment/launch_experiment.py:60: error: Argument 2 to "run_subprocess" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/deployment/launch_experiment.py:67: error: Argument 2 to "run_subprocess" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/deployment/launch_experiment.py:72: error: Argument 2 to "run_subprocess" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/deployment/launch_experiment.py:97: error: Argument 2 to "run_subprocess" has incompatible type "list[str]"; expected "str"  [arg-type]
src/swell/utilities/gsi_record_parser.py:1: error: Library stubs not installed for "pandas"  [import-untyped]
src/swell/utilities/gsi_record_parser.py:1: note: Hint: "python3 -m pip install pandas-stubs"
src/swell/utilities/gsi_record_parser.py:28: error: "None" has no attribute "loc"  [attr-defined]
src/swell/utilities/gsi_record_parser.py:28: error: Value of type "None" is not indexable  [index]
src/swell/utilities/gsi_record_parser.py:43: error: "None" has no attribute "iloc"  [attr-defined]
src/swell/utilities/gsi_record_parser.py:44: error: "None" has no attribute "iloc"  [attr-defined]
src/swell/utilities/gsi_record_parser.py:51: error: Value of type "None" is not indexable  [index]
src/swell/utilities/gsi_record_parser.py:54: error: "None" has no attribute "loc"  [attr-defined]
src/swell/utilities/gsi_record_parser.py:54: error: Value of type "None" is not indexable  [index]
src/swell/utilities/gsi_record_parser.py:65: error: "None" has no attribute "loc"  [attr-defined]
src/swell/utilities/gsi_record_parser.py:65: error: Value o [...]

2024-09-17 14:38 UTC, mranst commented
> Changes look good! However, when I ran this through a type checker locally (`mypy`), it turned up a bunch of errors. We don't have to address all (or even most, and perhaps not any) of them now...but I recommend taking a look through this list and deciding consciously which of the errors are worth fixing now and which ones we can wait on for a future PR.
> 
> @mranst I leave this up to your judgment. Let me know when you think we've hit a reasonably stopping point for this PR.
> 
> Full `mypy` output is in the Details below.

I've gone through the output of mypy and revised many of the more obvious mistypes I had, although there's still a lot of errors. A lot of them don't seem to necessarily be related to mistakes in type hinting, for instance it doesn't like any action being done on an optional parameter, although as far as I can tell most instances are valid per expected behavior. I feel like I've addressed most of the low-hanging fruit, but if you think I should go deeper, let me know

2024-09-17 14:48 UTC, ashiklom commented on src/swell/utilities/exceptions.py
> +        logger: Optional[pyLogger] = None
I think this is either a false positive with `mypy` or some issue in our Swell `Logger` implementation. I would change this back and flag it as something that should be revisited.

2024-09-17 14:51 UTC, ashiklom commented on src/swell/utilities/render_jedi_interface_files.py
> +        cycle_time: Union[Datetime, None],
```suggestion
        cycle_time: Optional[Datetime],
```

2024-09-17 14:59 UTC, ashiklom commented on src/swell/utilities/exceptions.py
> +        logger: Optional[pyLogger] = None
Or, if this really does support _either_ the Swell `Logger` class or the `logging.Logger` class, I would annotate it with a `Union[Logger, pyLogger]`, as you do below.

What we should _really_ do is make the Swell Logger a subclass of the `logging.Logger` class, so that we can (1) annotate all of these things as just `logging.Logger`, and, more importantly, (2) so that all of our Swell code can just use the `logging.Logger` without _needing_ to depend on the more specific Swell logging functionality. But...that's a bigger change that you definitely don't have to do here.

2024-09-17 15:02 UTC, ashiklom commented on src/swell/utilities/exceptions.py
> +        logger: Optional[pyLogger] = None
...but my inclination would be to keep this simple and just inherit from the Swell Logger class, and if there are interface differences, we should resolve those.

2024-09-17 15:03 UTC, ashiklom commented on src/swell/utilities/slurm.py
> +from logging import Logger as pyLogger
See comments above. My inclination would be to keep this simple --- just inherit from the Swell `Logger` class and, if there are interface differences, we need to fix the implementations.

2024-09-17 15:10 UTC, mranst commented on src/swell/utilities/exceptions.py
> +        logger: Optional[pyLogger] = None
This comes from `slurm_test.py`, which passes a `logging.Logger` object to `SwellError`. Currently it's behavior wouldn't support a swell logger object, though perhaps it should be reworked to just use a swell logger, as it seems to be the only instance of this

2024-09-17 15:14 UTC, ashiklom commented on src/swell/utilities/exceptions.py
> +        logger: Optional[pyLogger] = None
Ah, I see. I wrote `slurm_test`! In that case, let's keep this as is, but make a note (new GitHub issue!) to clean up our Logger usage and implementation.

2024-09-17 15:36 UTC, mranst commented on src/swell/utilities/exceptions.py
> +        logger: Optional[pyLogger] = None
Created issue #428

2024-09-17 15:38 UTC, ashiklom approved these changes, later dismissed

2024-09-17 16:54 UTC, ashiklom approved these changes

2024-09-17 16:54 UTC, merged