Cycling FGAT for marine
GEOS-ESM/swell pull request #419
Opened 2024-09-12 16:16 UTC by Dooruk

2024-09-24 21:31 UTC, ashiklom commented on src/swell/configuration/jedi/interfaces/geos_marine/model/background.yaml
> +{% if 'cice6' in marine_models %}
So, for reference, where I _personally_ want to see us get to is removing these YAML files altogether and replacing them with a Python dictionary that writes out YAMLs at runtime. E.g.,

```python
background = {
  "date": local_background_time,
  "read_from_file": 1,
  "basename": pathlib.Path('.'),
  #...
}

if 'cice6' in config.models.marine_models:
  background["ice_filename"]: f"cise.res.{local_background_time}"
  
# Some function to test that the background is valid
# Can have more complex logic about
validate_jedi_background(background)

# ...
# When we're ready to process the experiment
# ...
with open("path/to/experiment/jedi/geos_marine/background.yaml", "w") as f:
  yaml.dump(background, f)
```

2024-09-24 21:32 UTC, ashiklom commented on src/swell/configuration/jedi/interfaces/geos_marine/model/background.yaml
> +{% if 'cice6' in marine_models %}
That said, as a stopgap, what you have here is fine --- it's clear enough what's going on.

2024-09-24 21:41 UTC, ashiklom commented on src/swell/tasks/generate_b_climatology.py
> +                os.mkdir('background_error_model')
`os.chdir` is really fragile, and makes the code harder to reason about because you have to remember what the last time you called `os.chdir` was.

I strongly recommend avoiding it and just doing something like this here:

```python
background_error_model_dir = os.path.join(self.cycle_dir(), "background_error_model")
if not os.path.exists(background_error_model_dir):
  os.mkdir(background_error_model_dir)
```

For running subprocess commands, `subprocess` supports a `cwd` argument. I.e., Instead of:

```python
os.chdir("somewhere")
subprocess.run("some_command", ...)
```

...do...

```python
subprocess.run("somecommand", ..., cwd="somewhere")
```

I'm not sure if `run_track_log_subprocess` is set up to accept `cwd` as an (optional) argument. But if not, it should be! (More generally, all our `run_..._subprocess` commands should just accept `**kwargs` as an argument that gets propagated through to `subprocess.run(..., **kwargs)`.

2024-09-24 21:42 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +        if self.get_model() == 'geos_ocean' or self.get_model() == 'geos_marine':
Stylistically, I have a slight preference for the following. It's shorter, and IMHO, the intent is clearer.

```suggestion
        if self.get_model() in ('geos_ocean', 'geos_marine'):
```

2024-09-25 12:47 UTC, ashiklom commented on src/swell/suites/3dfgat_cycle/eva/increment-geos_marine.yaml
@asewnath Per my comment above, one thing I'd like you to explore (when you have the time) is defining a Python class, or set of Python classes composed together, (better yet: a [dataclass](https://docs.python.org/3/library/dataclasses.html) or [pydantic data model](https://docs.pydantic.dev/latest/)) that might ultimately replace YAML files like this.

I'm _inclined_ to think that using Python classes would be better, but it's hard to know exactly until we actually see a prototype implementation and try to do some stuff with it.

2024-09-25 12:57 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +        if self.window_type == '4D' or 'fgat' in self.suite_name():
This conditional spans this entire function, so I would suggest refactoring into distinct functions like `link_mom6_history_fgat` vs. `link_mom6_history_default` (or something), and then call them as:

```python
        if self.get_model() == 'geos_ocean' or self.get_model() == 'geos_marine':
            if `self.window_type == "4D" or 'fgat' in self.suite_name():
              self.link_mom6_history_fgat(self.src_dst_dict)
            else:
              self.link_mom6_history_default(self.src_dst_dict)
```

2024-09-25 13:00 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +        self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}
Do we expect this attribute to be used anywhere else in the class. If yes, then we can keep it as an attribute, but then, it probably makes sense to change the MOM6 method below to just take `self` as an argument and grab this attribute from `self`.

If not, then we can just make it a local variable and pass it to the method without the `self`.

2024-09-25 13:55 UTC, ashiklom commented on src/swell/utilities/data_assimilation_window_params.py
> +
First, the behavior of `dto=True/False` here is inconsistent with other functions that do this (like `window_start/end_iso`. Those functions return _either_ a datetime object or the string representation. Here, `dto=True` returns both.

Second, having a function return different kinds of things based on its arguments is called "type instability" and is a pattern that should be avoided. It's much better to either have these be either separate dedicated functions (e.g., `local_background_time` returns a datetime, `local_background_time_dir` returns a string) or use function composition:

```python
def date2dir(dt: datetime.datetime):
  return dt.strftime(datetime_formats["directory_format"])

def local_background_time(self, window_offset, window_type) -> datetime.datetime:
  return self.__get_local_background_time__(window_type, window_offset)

#  ...
some_directory = date2dir(local_background_time(...))
```

2024-09-25 13:56 UTC, ashiklom commented on src/swell/utilities/geos.py
> +        if model == 'geos_ocean' or model == 'geos_marine':
```suggestion
        if model in ("geos_ocean", "geos_marine"):
```

2024-09-25 14:00 UTC, ashiklom commented on src/swell/utilities/geos.py
> +            i += 1
Range can take a `start` and `stop` argument. So, if you want to skip `i=0`, you can just do:

```suggestion
        for i in range(1, number_of_states):
```

2024-09-25 16:56 UTC, asewnath commented on src/swell/tasks/link_geos_output.py
> +        self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}
`self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}` -> You can also instantiate a dictionary of lists using `defaultdict(list)`. This way, every time you have a new key, there will be an empty list associated with it that you can append to.

```
self.src_dst_dict = defaultdict(list)
self.src_dst_dict[src].append(dst)
```

This way, you don't have to force `dst` to be a tuple in order to add it to the `src` list

2024-09-25 16:56 UTC, asewnath commented on src/swell/tasks/link_geos_output.py
> +                self.src_dst_dict[src] = dst
`self.src_dst_dict` is typed as `Dict[str, Tuple[str, ...]]` but value is set to `dst`

2024-09-25 17:39 UTC, Dooruk commented
Thank you for the reviews! Before this one, the following needs to be merged:
https://github.com/GEOS-ESM/swell/pull/430

Then I will work on your suggestions.

2024-09-27 19:08 UTC, Dooruk commented on src/swell/tasks/generate_b_climatology.py
> +                os.mkdir('background_error_model')
Thanks, good suggestion! I will add `kwargs` to `shell_commands` utility.

2024-09-27 19:27 UTC, Dooruk commented on src/swell/tasks/link_geos_output.py
> +        if self.get_model() == 'geos_ocean' or self.get_model() == 'geos_marine':
Thanks, great suggestion!

2024-09-27 20:07 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_marine/model/background.yaml
> +{% if 'cice6' in marine_models %}
ok, marking this as resolved for now.

2024-10-07 16:17 UTC, Dooruk commented on src/swell/tasks/link_geos_output.py
> +        self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}
I will stick with `self.` approach as this task may be handling different model outputs

2024-10-07 16:25 UTC, Dooruk commented on src/swell/tasks/link_geos_output.py
> +        self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}
I found out using Tuple was unnecessary, is there an advantage of using `defaultdict(list)` vs. `{}` if that's the case?

2024-10-07 16:43 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +        self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}
With `defaultdict(list)`, the following will _always_ work, for any value of `key`, regardless of whether or not the corresponding key exists in the dict. That's because `x[key]` is automatically initialized to a blank list for any missing value of `key`.

```python
x = defaultdict(list)
x[key].append(something)
```

Without `defaultdict`, the above would almost certainly throw an error, and you would need to write much uglier and more brittle code along the lines of:

```python
x = {}
x[key] = x[key] + [something] if key in x else [something]
```

2024-10-07 17:24 UTC, Dooruk commented
I'm still struggling with `kwargs`. I tried @mranst's suggestion `Union[int, str, None] = None` but that didn't work unfortunately. For now I commented it out but I will test the rest of this PR and come back to it.

Also, following @ashiklom's suggestion on using `cwd` for `subprocess`, I will not providing a default so it will be `cwd: str`. Hence, it will always throw an error if it's not defined, I think that makes sense?. This is the part I'm talking about: 

https://github.com/GEOS-ESM/swell/blob/597bbbe9c87867178a130a10c6d07418d1a212d8/src/swell/utilities/shell_commands.py#L21-L25

2024-10-07 18:47 UTC, Dooruk commented on src/swell/utilities/data_assimilation_window_params.py
> +
Good suggestion. This impacts quite a few tasks and suites so it won't be straightforward. Let me address this in a separate issue.

2024-10-07 19:26 UTC, ashiklom commented
`**kwargs` don't need to be type hinted. The main situation in which you _would_ type hint them is if all the arguments had the same type (e.g., every `**kwargs` was an integer). If that's not the case, then the type hint is confusing and, more importantly, defeats a lot of the flexibility of using `kwargs` in the first place.

Unfortunately, type hinters don't seem to be smart enough to propagate type checking through `kwargs`, but that's OK --- we shouldn't let the perfect be the enemy of the good!

If you use `**kwargs`, you don't need to propagate the `cwd` argument directly. However, if you want to propagate it anyway, I would just follow the semantics of the parent function [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run) and default to `cwd: Optional(str) = None`, where `cwd = None` means use the current working directory.

2024-10-09 20:15 UTC, asewnath commented on src/swell/tasks/link_geos_output.py
> +        self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}
> I found out using Tuple was unnecessary, is there an advantage of using `defaultdict(list)` vs. `{}` if that's the case?

It depends on why it is unnecessary. If the tuple is unnecessary because you only expect one value for every key, then you don't need to use defaultdict, and you can use {} instead.

2024-10-10 14:32 UTC, Dooruk commented on src/swell/tasks/link_geos_output.py
> +        self.src_dst_dict: Dict[str, Tuple[str, ...]] = {}
Unnecessary because I thought I needed to have different values sharing the same key but that turned out not to be the case..

2024-10-10 15:43 UTC, Dooruk commented
So I have one issue (more of a design flaw 🥲  ) left related to low-level design of task/suite/experiment config creation but this is good to go. For now I will set a hard-coded value in the task and move on but I can also create an issue depending on the comments.

The issue arises a key in `task_questions.yaml` or `suite_questions.yaml` needs to be used by a conditional task in `flow.cylc`.  Following is the entry in my `task_questions.yaml`. I don't see `cice6_domains` in my `experiment.yaml` after `swell create` step:

```yaml
cice6_domains:
  ask_question: true
  default_value: defer_to_model
  models:
  - geos_marine
  options: defer_to_model
  prompt: Which CICE6 domains do you wish to run DA for?
  tasks:
  - RunJediConvertStateSoca2ciceExecutable
  type: string-check-list
```

Only the `RunJediConvertStateSoca2ciceExecutable` task requires this. In `flow.cylc`, this task is used only when `cice6` is active:

```cylc
    {% if 'cice6' in marine_models %}

    [[RunJediConvertStateSoca2ciceExecutable-{{model_component}}]]
        script = "swell task RunJediConvertStateSoca2ciceExecutable $config -d $datetime -m {{model_component}}"
        platform = {{platform}}
        execution time limit = {{scheduling["RunJediConvertStateSoca2ciceExecutable"]["execution_time_limit"]}}
        [[[directives]]]
        {%- for key, value in scheduling["RunJediConvertStateSoca2ciceExecutable"]["directives"][model_component].items() %}
            --{{key}} = {{value}}
        {%- endfor %}

    {% endif %}
```
While creating `experiment.yaml`, Swell scans `flow.cylc` `[runtime]` section to find unique tasks and hence to define associated `questions (keys)` in `task_questions.yaml`. `marine_models` was not defined during this non-exhaustive search step, hence this task inside the conditional is essentially not registered. I'm talking about at this stage of the code:

https://github.com/GEOS-ESM/swell/blob/597bbbe9c87867178a130a10c6d07418d1a212d8/src/swell/deployment/prepare_config_and_suite/prepare_config_and_suite.py#L382

Here, `self.experiment_dict` contains `model_components` so tasks inside those conditionals work:

```cylc
    {% for model_component in model_components %}

    [[LinkGeosOutput-{{model_component}}]]
        script = "swell task LinkGeosOutput $config -d $datetime -m {{model_component}}"
    {% endfor %}
```

Anyways, this was really long explanation but happy to explain even further, I had to do some digging to find this issue.

2024-10-10 16:37 UTC, ashiklom requested changes

2024-10-10 16:37 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +    def link_cice6_history_4d(self) -> Tuple[str, str]:
This has no `return` statement, so it returns `None`, _not_ a Tuple.

```suggestion
    def link_cice6_history_4d(self) -> None:
```

2024-10-10 16:37 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +    def link_cice6_history_3d(self) -> Tuple[str, str]:
Ditto here.

```suggestion
    def link_cice6_history_3d(self) -> None:
```

2024-10-10 16:37 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +                              ) -> Tuple[str, str]:
Ditto here.

```suggestion
                              ) -> None:
```

2024-10-10 16:37 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +    def link_mom6_history_3d(self) -> Tuple[str, str]:
```suggestion
    def link_mom6_history_3d(self) -> None:
```

2024-10-10 16:37 UTC, ashiklom commented on src/swell/tasks/link_geos_output.py
> +    def link_mom6_history_4d(self) -> Tuple[str, str]:
```suggestion
    def link_mom6_history_4d(self) -> None:
```

2024-10-10 16:37 UTC, ashiklom commented on src/swell/utilities/data_assimilation_window_params.py
> +    def local_background_time(self, window_offset, window_type, dto=False) -> str:
This can return either a string or a tuple of a string and a datetime. So, the correct type hint should be something like:

```suggestion
    def local_background_time(self, window_offset, window_type, dto=False) -> Union[str, Tuple[str, datetime]]:
```

(If we're using Python >= 3.10, then this can be written more concisely as: `str | Tuple[str, datetime]`).

While I'm pontificating, in the future, I would just drop the `dto` argument, change this function to _always_ return the background time as the second argument, and then just use tuple unpacking to absorb the unused argument whenever we don't need it.

```python
mystring, _ = self.local_background_time(window_offset, window_type)
# Python will put the datetime into the `_`, which is then silently discarded.
```

2024-10-11 13:35 UTC, Dooruk commented on src/swell/tasks/link_geos_output.py
> +    def link_cice6_history_4d(self) -> Tuple[str, str]:
oops..

2024-10-11 13:37 UTC, Dooruk commented on src/swell/utilities/data_assimilation_window_params.py
> +    def local_background_time(self, window_offset, window_type, dto=False) -> str:
I will revisit the `dto` with the issue I created. I agree it's confusing in it's current form.

2024-10-16 14:16 UTC, ashiklom approved these changes
Someone else should review the DA aspects, but code looks good. Appreciate the documentation!

2024-10-16 17:25 UTC, merged