Add hydrometeors
GEOS-ESM/swell pull request #422
Opened 2024-09-12 20:28 UTC by rtodling

## Description

This adds hydrometeors and changes to the linear obs operators necessary to account for sensitivity of all-sky MW to such fields.

## Dependencies

- [https://github.com/JCSDA-internal/fv3-jedi/pull/1257 ] waiting on fv3-jedi 
- [ https://github.com/JCSDA-internal/saber/pull/939] waiting on saber

## Impact

None other

2024-09-13 19:34 UTC, rtodling commented
Look around to try to understand some - unrelated to this - I came across the fact that by default, the hydrometeors radii is set to use GFDL's numbers ... the GSI numbers are an option ... The yaml's for GMI and AMRS2 in swell are using the fv3-jedi default which is not what we want - I believe. 

I ran a little test w/ GMI obs only to see what difference we get from these two schemes in comparison to GSI: I find that the difference between the two schemes is considerable smaller than the difference of either scheme w/ the actual GSI. Here is an illustration of the differences: top: GSI-minus-fv3-jedi using GSI radii; bottom: diff of JEDI increments when using either GSI or GFDF radii ...

<img width="582" alt="qr_radii_schemes" src="https://github.com/user-attachments/assets/867c5f00-0cf1-413e-b574-c6d92810ac6f">

The differences in the temperature are unnoticeable either way - GSI and JEDI are quite good match to each other regardless of which scheme is used - no need to show.

In any case, the consistent choice of radii is also being introduced in the changes presented here.

2024-09-25 16:13 UTC, rtodling commented
The PRs from JEDI mentioned above have been merged. I believe the changes here could now make it into SWELL

2024-09-25 17:27 UTC, Dooruk commented
@rtodling Can you set the environment `LOG_INFO` variable to 1 and run `swell test code_tests` with this branch please? There is a code testing issue.

https://geos-esm.github.io/swell/#/code_tests/code_tests

2024-09-25 21:04 UTC, Dooruk commented
This will require a JEDI build post ~September 20th.

2024-10-24 18:16 UTC, rtodling commented
@Dooruk All tests seem to have passed for this - can we take this in? If not, can we chat?

2024-10-24 18:18 UTC, Dooruk commented
> @Dooruk All tests seem to have passed for this - can we take this in? If not, can we chat?

Did you run t1tests? I will fire it up in github actions now

2024-10-24 18:25 UTC, rtodling commented
> > @Dooruk All tests seem to have passed for this - can we take this in? If not, can we chat?
> 
> Did you run t1tests? I will fire it up in github actions now

I was looking in the doc how as I user I can fire up the tier-1 test ... but it's not quite clear to me.

2024-10-24 18:29 UTC, Dooruk commented
Doesn't this require the new JEDI build by the way?

2024-10-24 18:49 UTC, Dooruk requested changes
So overall, there are issues regarding `get_values` and file permissions were changed. These changes are breaking ocean 3dvar.

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/oops/LocalEnsembleDA.yaml
> +  get values:
When you put anything in the OOPS part of SWELL this will impact the marine side as well if it's a generic application. So for this, we don't have a corresponding `get_values.yaml` on the `geos_ocean` side and `3dvar` is complaining. One option is that I can create an dummy `get_values.yaml` which is fine.

However when I searched for this `get values` key in the SWELL source code I see sections that modifies that behavior, see below, so we have to be careful with this:

https://github.com/GEOS-ESM/swell/blob/2b0f03bf30e2782b8441657f9be86558e63e5436/src/swell/tasks/run_jedi_ufo_tests_executable.py#L87-L93

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/oops/hofx3D.yaml
> +  get values:
Same above^

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/oops/variational3D.yaml
> +    get values:
Same above^

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/oops/variational4D.yaml
> +    get values:
Same above^

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/geometry.yaml
Did you accidentally changed the file permissions here?

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/background.yaml
permission issue

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/background_ensemble.yaml
Did you accidentally changed the file permissions here?

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/geometry_inner.yaml
permission

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/pseudo-model.yaml
permission

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/r2d2.yaml
permission

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/stage.yaml
permission

2024-10-24 18:49 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/stage_cycle.yaml
permission

2024-10-25 12:44 UTC, rtodling commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/geometry.yaml
Ok - 1st to the file permissions: not accidental - I don't see any reason for yaml files to be executable file, unless I am missing something, am I?

2024-10-25 12:53 UTC, rtodling commented on src/swell/configuration/jedi/oops/hofx3D.yaml
> +  get values:
What's the correct way of handling this?  I am completely surprised and puzzled as to why  the UFO tasks are removing  the "get values" entries ... but then again, I don't care too much about those tests. 

So the important thing for me is to have "get values" properly appear in the Var cases ... which as far as I know they do. Now, I didn't think of that upsetting the marine apps ... so I agree that something else would need to be done to avoid that - perhaps as you say, implementing an empty "get values"

2024-10-25 12:57 UTC, rtodling commented on src/swell/configuration/jedi/oops/LocalEnsembleDA.yaml
> +  get values:
As I say below, I personally see no reason why an entry that's used in the Var should not be present in the UFO test; that makes the UFO test inconsistent w/ the Var ... but also, as I say below, I don't particularly care too much about what's being done in these tests. What I care about is for the Var opts/settings to come out correctly - and believe they do .... as look at the final yaml file in my Var runs.

2024-10-25 15:03 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/model/geometry.yaml
Sounds good, wanted to make sure nothing was changed unintentionally.

2024-10-25 15:26 UTC, Dooruk approved these changes
all good

2024-10-25 15:36 UTC, merged