LGETKF: add function to tune horizontal localization for each observer
GEOS-ESM/swell pull request #437
Opened 2024-10-02 15:18 UTC by metdyn

## Description

This PR adds a mechanism to customize horizontal localization (e.g.,  Gaspari-Cohn) for obs in LGETKF.

- add a directory /jedi/interfaces/geos_atmosphere/observations/localization
- each yaml in that directory is used to update localization for the corresponding observer

## Dependencies

## Impact

2024-10-03 13:56 UTC, metdyn commented
Offline for improvement

2024-11-13 13:43 UTC, Dooruk commented
A quick question, did we confirm having `localization` in observation YAMLs break the Variational applications?

2024-11-14 20:13 UTC, metdyn commented
> A quick question, did we confirm having `localization` in observation YAMLs break the Variational applications?
@Dooruk, the added directory `jedi/interfaces/geos_atmosphere/observations/localization` is used by local ensemble da only.   And other modifications are in 
```
M       src/swell/tasks/run_jedi_local_ensemble_da_executable.py
M       src/swell/test/suite_tests/localensembleda-tier1.yaml
```
This PR does not affect variational runs.

2024-11-19 14:12 UTC, Dooruk requested changes
This is good to go with two minor changes. One is in the review the other is a simple change in this branch here, that needs to be added to run `3dvar_atmos` on Milan nodes:

`feature/tasks_per_node`

Could you make that line change in this branch so we could merge this PR? @rtodling do you have any comments?

2024-11-19 14:12 UTC, Dooruk commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +                                         f'/observations/localization')
Could we use the `importlib` to define `path` here?

You can see Alexey's justification here:

https://github.com/GEOS-ESM/swell/pull/429#discussion_r1763612715

2024-11-20 21:43 UTC, metdyn commented on src/swell/tasks/run_jedi_local_ensemble_da_executable.py
> +                                         f'/observations/localization')
possible, but we can do it more systematically later on.

2024-11-23 05:47 UTC, Dooruk approved these changes

2024-11-23 05:51 UTC, Dooruk commented
I don't want to hold back this any longer, thanks @metdyn for working on this.

@mranst just FYI the `3dvar` suite doesn't work on SLES15 in the `gmao_ci` context so tier1 test will break, but `3dvar` suite works locally on my end with defaults. I'm a bit puzzled. I will merge this PR and look into the issue, I suspect something to do with the node allocations.

2024-11-23 05:52 UTC, merged