replace aircraft bias CSV files with new nc4 files to use with updated bias correction
GEOS-ESM/swell pull request #478
Opened 2024-12-04 22:59 UTC by gmao-msienkie

## Description

Several scripts are updated to remove reference to the CSV bias files and enable generation and use of the new netCDF4 format files.

## Dependencies

- [ ] waiting on GEOS-ESM/repo/pull/<pr_number>
- [ ] waiting on GEOS-ESM/repo/pull/<pr_number>

## Impact

- [ ] repo
- [ ] ...

2024-12-05 00:13 UTC, gmao-msienkie commented
My code has 'ascent rate' where the develop had had the ridiculous 'windUpward' before.  I guess 'instantaneousAltitudeRate' is OK too.

2024-12-07 01:35 UTC, gmao-msienkie commented
current status:
- The updated src/swell/tasks/gsi_bc_to_ioda.py seems to be working okay 
- For src/swell/tasks/get_observations.py I gave the aircraft coefficient file the type 'satbias' which mean I also had to provide a fake satbias_pc file.  I didn't think I wanted to stick with 'csv'.  Maybe at some point the r2d2 could use the newer name "obsbias_coefficients" in r2d2.  I have some sample files stored in my R2D2DataStore on nobackup
- The RunJediHofxExecutable task fails. "Bad parameter: getAllIndices: Can't find element in the vector"  The bias correction configuration was copied from ufo/test/testinput/instrumentTests/Aircraft_obs/aircraft_geos_qc.yaml

2024-12-07 16:09 UTC, gmao-msienkie commented
current status:
- The updated src/swell/tasks/gsi_bc_to_ioda.py seems to be working okay 
- For src/swell/tasks/get_observations.py I gave the aircraft coefficient file the type 'satbias' which mean I also had to provide a fake satbias_pc file.  I didn't think I wanted to stick with 'csv'.  Maybe at some point the r2d2 could use the newer name "obsbias_coefficients".  I have some sample files stored in my R2D2DataStore on nobackup
- The RunJediHofxExecutable task fails. "Bad parameter: getAllIndices: Can't find element in the vector"  The bias correction configuration was copied from ufo/test/testinput/instrumentTests/Aircraft_obs/aircraft_geos_qc.yaml

2025-01-29 19:53 UTC, gmao-msienkie commented
I modified the title to try to make clear that the CSV files are not being converted, rather that the original text GSI bias coefficient files will be converted to NC4 format files.
Any existing CSV bias coefficient files can be replaced with NC4 files converted directly from the GSI bias coefficient files.

2025-02-01 16:06 UTC, rtodling commented
@gmao-msienkie I just pulled your branch and tried setting a 3dvar case ... the GetObservation task fails due to not finding the new bias correction (nc4) file ... I assume you are pointing to a location of yours that has such files - that is, you probably have an r2d2_config.yaml that allows for the proper testing. Can you point me to that, please?

2025-02-03 19:37 UTC, Dooruk requested changes
I tested running ncdiag, because of the way filenames changed we need to do a few changes but other than that it should be good to go.

And this needs to be merged with develop. @gmao-msienkie I can handle those changes.

2025-02-03 19:37 UTC, Dooruk commented on src/swell/tasks/get_observations.py
> +#                   os.chmod(target_file, 0o644)
```suggestion
```

2025-02-03 19:37 UTC, Dooruk commented on src/swell/tasks/get_observations.py
> +                      file_type='satbias')
```suggestion
                      file_type='acftbias')
```

2025-02-03 19:37 UTC, Dooruk commented on src/swell/tasks/get_observations.py
> +                      file_type='satbias')
I will create this extension in R2D2, this is still an nc4 file but R2D2 needs this extension..

2025-02-03 19:37 UTC, Dooruk commented on src/swell/configuration/jedi/interfaces/geos_atmosphere/observations/aircraft.yaml
> +  input file: '{{cycle_dir}}/aircraft_abias_air.{{window_begin}}.nc4'
```suggestion
  input file: '{{cycle_dir}}/aircraft_abias_air.{{window_begin}}.acftbias'
```

2025-02-04 16:43 UTC, Dooruk commented
Ok, this works for x0050 only.  However only for 2023/10/10 and backgrounds has to come outside of R2D2. @rtodling please give it a shot and see if c180 background works or if we need to adjust that as well.

2025-02-04 16:43 UTC, Dooruk commented
thank you  @gmao-msienkie for adding this.

2025-02-04 16:46 UTC, Dooruk approved these changes, later dismissed

2025-02-06 13:41 UTC, rtodling commented
I just pushed the split of aircraft into temperature and wind individual ob-spaces - the bias correction inflation filter for temperature is not working - it needs an update to be consistent with latest JEDI.

EVA is still not working so, the 3dvar suite fails due to that ... looking into it.

2025-02-06 13:47 UTC, rtodling commented
There is other stuff missing - like in the UFO testing and the corresponding split in yaml info

2025-02-06 14:19 UTC, Dooruk commented
@rtodling, I don't see the `aircraft_wind` or `aircraft_temperature` yamls in the observation folder, just that you erased the `aircraft.yaml`.

2025-02-06 14:20 UTC, Dooruk commented
You need to update `src/swell/configuration/jedi/observation_ioda_names.yaml` as well

2025-02-06 18:35 UTC, Dooruk commented
When did this JEDI change go in? What version (time-wise) of JEDI do we need Aircraft to work?

2025-02-12 15:02 UTC, rtodling approved these changes
As far as I know everything is good to go.

2025-02-12 15:16 UTC, merged